<?php

namespace Webhines\SymbinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{

    public function search ($q) 
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT d FROM WebhinesSymbinBundle:Document d WHERE d.title like :qry OR d.body like :qry ORDER BY d.updated_at DESC'
            )->setParameter('qry', '%' . $q . '%')
            ->getResult();
    }
}
